# Generated by Django 4.2.3 on 2023-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField()),
                ('area', models.CharField(blank=True, max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('sumario', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('url_imagen', models.URLField(blank=True)),
                ('boton', models.CharField(blank=True, choices=[('Ver más', 'Ver más'), ('Ver video', 'Ver video'), ('Sumate', 'Sumate'), ('Inscribite', 'Inscribite')], max_length=20)),
                ('Orden', models.IntegerField()),
            ],
        ),
    ]
