# Generated by Django 4.2.3 on 2023-08-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_diario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedades',
            old_name='Orden',
            new_name='orden',
        ),
    ]
