# Generated by Django 4.2.3 on 2023-08-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Laboral', 'Laboral'), ('Impuestos', 'Impuestos'), ('Sociedades', 'Sociedades'), ('Contabilidad', 'Contabilidad'), ('Buenos Aires', 'Buenos Aires'), ('Córdoba', 'Córdoba'), ('Santa Fe', 'Santa Fe'), ('Rural', 'Rural'), ('Liquidación de sueldos', 'Liquidación de sueldos')], max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NovedadEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('sumario', models.TextField()),
                ('link', models.URLField()),
                ('boton', models.CharField(max_length=50)),
                ('tipo_norma', models.CharField(blank=True, max_length=50)),
                ('organismo', models.CharField(blank=True, max_length=50)),
                ('nro_norma', models.CharField(blank=True, max_length=50)),
                ('jurisdiccion', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EReportNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('e_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='ereports.ereport')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ereports.novedadereport')),
            ],
        ),
    ]
