# Generated by Django 4.2.3 on 2023-08-02 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ereportnovedad',
            name='e_report',
            field=models.ForeignKey(limit_choices_to={'fecha': datetime.date(2023, 8, 2)}, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='ereports.ereport'),
        ),
    ]
