# Generated by Django 4.2.3 on 2023-08-03 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereports', '0003_alter_novedadereport_boton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ereportnovedad',
            name='e_report',
            field=models.ForeignKey(limit_choices_to={'fecha': datetime.date(2023, 8, 3)}, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='ereports.ereport'),
        ),
        migrations.AlterField(
            model_name='novedadereport',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ConsultasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='Consultas frecuentes', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('consulta', models.TextField()),
                ('respuesta', models.TextField()),
                ('e_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='ereports.ereport')),
            ],
        ),
        migrations.AddField(
            model_name='ereport',
            name='consultas_frecuentes',
            field=models.ManyToManyField(related_name='consultas_frecuentes', to='ereports.consultasfrecuentes'),
        ),
    ]
