# Generated by Django 4.2.3 on 2023-08-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ereports', '0004_alter_ereportnovedad_e_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ereport',
            name='consultas_frecuentes',
        ),
        migrations.DeleteModel(
            name='ConsultasFrecuentes',
        ),
    ]
