# Generated by Django 4.2.3 on 2023-08-03 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ereports', '0005_remove_ereport_consultas_frecuentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadereport',
            name='sumario',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
