# Generated by Django 4.2.3 on 2023-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereports', '0006_alter_novedadereport_sumario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadereport',
            name='sumario',
            field=models.TextField(blank=True),
        ),
    ]
